language: go

go:
 - tip

install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

before_script:
 - go vet -v ./...

script:
 - go test -v -bench=. ./...
 - go test -v -covermode=count -coverprofile=coverage.out ./dcmdata
 - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
