version: 1.0.{build}
image: Visual Studio 2017
platform: x64

branches:  
  only:
    - master

clone_folder: 'c:\workspace\go\src\github.com\grayzone'
environment:
  GOROOT: c:\go
  GOPATH: c:\workspace\go

install:  
  - echo %PATH%
  - echo %GOPATH%
  - choco upgrade all -y
  - choco install mingw
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\tools\MinGW64\bin;%PATH%
  - go version
  - go env

  - go get -v -d -t github.com/grayzone/godcm/...

build_script:  
  - go test -v -cover github.com/grayzone/godcm/...
